version: "3"
services:
  app:
    image: danielwisky/filmoteca
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:3.6.1
    container_name: "filmoteca-mongodb"
    ports:
      - 27017:27017
    command: --smallfiles